name: Gerar animação da cobra

on:
  schedule: 
    - cron: "* */12 * * *" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Geração do snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
